### ISSUE TITLE
PyAlarm on Windows

### ISSUE THREAD

**Issue by NexeyaSGara** [sergirubio/panic#2]
Hi,

Maybe it's related to the fandango can't import resource on windows, but I'm getting this when I try to start PyAlarm.

UNABLE TO LOAD SMSLIB OR SMSMODEM ... SMS MESSAGING DISABLED
In PyAlarmClass  constructor
Variables property NOT found in database
StartupDelay property NOT found in database
PhoneBook property NOT found in database
AllowedActions property NOT found in database
FromAddress property NOT found in database
SMSConfig property NOT found in database
In DynamicDSClass.**new**(<class 'fandango.device.DDebug.DDebugClass'>): updating properties
DynamicSpectrumSize property NOT found in database
-------> Received a DevFailed exception: DevFailed[
DevError[
    desc = AttributeError: 'Alarm' object has no attribute 'reset_receivers'

  origin =   File "C:\Python27\lib\site-packages\PyTango\device_class.py", line 553, in **DeviceClass__device_factory
    device = self._new_device(deviceImplClass, klass, dev_name)
  File "C:\Python27\lib\site-packages\PyTango\device_class.py", line 533, in __DeviceClass__new_device
    return klass(dev_class, dev_name)
  File "C:\Python27\Lib\site-packages\PyAlarm\PyAlarm.py", line 943, in __init**
    PyAlarm.init_device(self,allow=True)
  File "C:\Python27\Lib\site-packages\PyAlarm\PyAlarm.py", line 1096, in init_device
    raise e

  reason = PyDs_PythonError
severity = ERR]
]

**Comment by sergirubio** [comment]
Hi Sebastièn,

Actually, I don't support Panic on Windows due to the lack of time to test it. Sorry. Could you try to reproduce the same issue on a linux system?

I also warn you that the repository for Panic is now github.com/tango-controls/PANIC; I'll close this other repository in a few days.

I will add a note to the Panic README warning about Windows not supported, Sorry

Sergi

**Comment by NexeyaSGara** [comment]
Hi, I know that 99% of users are on Linux, I wanted to try to see.
I will use the other repository.
When I had some time, I will try to reproduce it on Linux.
I will also try to fix what's missing to be compatible windows.
Thanks

**Comment by NexeyaSGara** [comment]
In fact, I think I had an old version messing with the new. I did try from a fresh install of the tango-cs verions, and it seems to be working. The only thing is with the import resource not available on Windows.
Sorry for the "false" issue

**Comment by sergirubio** [comment]
And what about the problem on "New Alarm" from the GUI ... does it work well, then?

**Comment by NexeyaSGara** [comment]
Yes, it's working well.

I was still executing the code from the old directory structure (PyAlaram directory.....).

I was thinking that the reset_receivers was integrated into the master branch
